name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fast-cove-79483"
          heroku_email: "jasse.nousiainen@gmail.com"
          healthcheck: "https://fast-cove-79483.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
      - if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          if: ${{ job.status == 'success' }}
            args: A new version deployed to https://fast-cove-79483.herokuapp.com/